# Generated by Django 4.0.3 on 2022-04-27 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_article_remove_articles_iduser_delete_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idComment', models.AutoField(db_column='idComment', primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('idArticle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.article')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
