# Generated by Django 4.0.3 on 2022-05-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temoignages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoignage',
            name='img',
            field=models.ImageField(upload_to='static/medias'),
        ),
    ]
