# Generated by Django 4.0.3 on 2022-04-27 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.AutoField(db_column='idCategory', primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('idParent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='category.category')),
            ],
        ),
    ]
