# Generated by Django 4.0.3 on 2022-04-27 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domaine_article', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('idArticle', models.AutoField(db_column='idArticle', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='medias')),
                ('status', models.BooleanField(default=True)),
                ('createDate', models.DateField()),
                ('updateDate', models.DateField()),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='category.category')),
                ('idDomaine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='domaine_article.domaine')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='idUser',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
