# Generated by Django 4.0.3 on 2022-05-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_remove_articles_iduser_delete_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(upload_to='static/medias'),
        ),
    ]
