# Generated by Django 4.0.3 on 2022-04-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chiffre',
            fields=[
                ('idChiffre', models.AutoField(db_column='idChiffre', primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('icon', models.ImageField(upload_to='medias/icons')),
            ],
        ),
    ]
