# Generated by Django 4.0.3 on 2022-05-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domaine_article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaine',
            name='icon',
            field=models.ImageField(upload_to='static/medias/icons'),
        ),
    ]
