# Generated by Django 4.0.3 on 2022-05-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('idMission', models.AutoField(db_column='idMission', primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='static/medias/icons')),
            ],
        ),
    ]
