# Generated by Django 4.0.3 on 2022-04-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('idBureau', models.AutoField(db_column='idBureau', primary_key=True, serialize=False)),
                ('pays', models.TextField()),
                ('adresse', models.TextField()),
                ('tel', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('focus', models.TextField()),
            ],
        ),
    ]
